### ISSUE TITLE
Graph builder error "no such directory memory:/"

### ISSUE THREAD

**Issue by alexswan10k** [ggoodman/velcro#19]
Error: 
```
react-dom.development.js:11865 Uncaught GraphBuildError: Graph building failed with errors:
No such directory memory:/ at
 GraphBuilder.doAddUnresolvedUri:memory:/index.js
    at GraphBuilder.buildGraph (http://localhost:8080/public/148.js:1884:19)
```

Code sample as follows:
```
import * as Velcro from "@velcro/runner";
...
    const code = `
      console.log("I am a trivial sample");
    `;
    Velcro.execute(code, {
      readUrl: u => {
        console.log("fetching", u)
        return fetch(u).then(u => u.arrayBuffer())
      },
      external: (x) => {
        return false;
      },
      injectModules: {
      },
      dependencies: {},
      nodeEnv: "production"
    })

```
As discussed this also fails upon the (sandbox demo)[https://plnkr.co/edit/sDnzv3QEv6wudM9P].

Original findings:

I have had a go at trying to hook all this up, with little avail unfortunately. I keep hitting the same error as seen on the sandbox, after having tried various combinations of the new runner or composing these constructs myself.

I am pretty sure I have narrowed it down to the listEntries first line in memoryStrategy.ts

The offending line:

Uri.ensureTrailingSlash(uri).fsPath
where fsPath seems to be returning a backslash rather than a forward slash, which is then fed into getEntryAtPath, which then resolves a parent as undefined, as no segment/child can be found matching "\" obviously!

I cant seem to locate fsPath on Uri or the builtin URL prototype, so perhaps you can help me work out where this is coming from?

I also noticed an inconsistency between Uri.parse('memory:///') and the generated Uri("memory:/directory/path"). Not sure if this is a problem though, i just cant rule it out yet either.

**Comment by ggoodman** [comment]
Lemme know if this fixes what you're seeing. I think it should given that there is now automatic testing in different node versions and OS flavours.

**Comment by alexswan10k** [comment]
Tested and working as intended. Thanks
