### ISSUE TITLE
Setting up the environment

### ISSUE THREAD

**Issue by alexswan10k** [ggoodman/velcro#25]
Thought I would just post a new issue for this to iron everything out, as I think there are still some steps missing.

Steps so far:
npm install lerna -g
(I tried npx but it just kept blowing up on "could not find lerna@latest)

goto root
git clean -fdx
npm install
lerna bootstrap
npm run test

Tests run, but all fail, following error:
ReferenceError: describe is not defined.

Have tried:
https://stackoverflow.com/questions/55807824/describe-is-not-defined-when-installing-jest
and installing:
https://www.npmjs.com/package/eslint-plugin-jest
but no avail.

Any thoughts?

**Comment by alexswan10k** [comment]
node -v    --v10.14.1
npm -v     --6.4.1
lerna -v    -- 3.21.0

**Comment by ggoodman** [comment]
Hi @alexswan10k I've tried to start from a clean slate and follow the bootstrapping steps. Note that I don't install `lerna` globally but instead rely on the version installed within the repo via `npx lerna`.

```
Projects/velcro % find . -type d -name 'node_modules'

Projects/velcro % node -v
v12.16.3

Projects/velcro % npm -v
6.14.5

Projects/velcro % npm i
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
added 1376 packages from 632 contributors and audited 1377 packages in 20.129s

39 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Projects/velcro % npx lerna bootstrap
lerna notice cli v3.21.0
lerna info Bootstrapping 9 packages
lerna info Installing external dependencies
lerna info Symlinking packages and binaries
lerna success Bootstrapped 9 packages

Projects/velcro % npm test

> velcro@0.0.0 test /Users/ggoodman/Projects/velcro
> jest

 PASS   @velcro/bundler  packages/@velcro/bundler/src/graph/parser/js/parser.test.ts (5.185 s)
 PASS   @velcro/strategy-cdn  packages/@velcro/strategy-cdn/src/cdnStrategy.test.ts (6.44 s)
 PASS   Integration tests  __test__/resolver.ts (6.683 s)
 PASS   Integration tests  __test__/runner.ts (10.123 s)

Test Suites: 4 passed, 4 total
Tests:       11 passed, 11 total
Snapshots:   2 passed, 2 total
Time:        10.712 s
Ran all test suites in 3 projects.
```

I'm really not sure what's missing on your setup. I don't think anything should require node 12...?

**Comment by ggoodman** [comment]
Given that this seems to be working as described in CI, I think it should work locally as well. Let me know if you're still seeing issues.

**Comment by alexswan10k** [comment]
If its working on the CI then its definitely something my end. Sorry for the delay been juggling a bunch of stuff, but I will 'adjust my environment' to whatever the CI is doing and see if that fixes. Cheers.

**Comment by alexswan10k** [comment]
Just to follow up on this, I upgraded to node 12, and all my problems went away! There must be a feature in one of the rollup plugins that requires node 12 I guess, and there is thus no node version constraint on the package.

npx lerna bootstrap now works correctly too (npx was broken before).
