### ISSUE TITLE
(query) - ESModules

### ISSUE THREAD

**Issue by alexswan10k** [ggoodman/velcro#29]
What are thoughts on ESModules and how they might fit into Velcro?

I appreciate that this has been the future for 10 years now, and because of the lack of bare import specifiers, they have been mostly useless. 

I was chatting to one of the guys over at bit.dev, and he mentioned that their package CDN will be based around esmodules as they have somewhat more control over the output process. He also mentioned the notion of [import maps](https://github.com/WICG/import-maps) which may well be the missing link required.

**Comment by ggoodman** [comment]
Hi @alexswan10k, I've thought about ES Modules quite a bit. My main challenge is finding a _minimal_ way to do the commonjs --> esm transform so that it continues to work in the browser and doesn't double the size of Velcro itself.

I've thought a bit about ripping out some of Rollup's internals and the `@rollup/plugin-commonjs` but haven't really built up the motivation to go that far.

I am away of import maps, and in fact, if you look at the generated bundles they essentially have partial, per-source-module import maps that are used by the runtime to map specifiers to resolved uris.

**Comment by alexswan10k** [comment]
I guess if you wanted to normalise around cjs [babel](https://babeljs.io/docs/en/babel-plugin-transform-modules-commonjs) can do these transforms, but its a large bundle as you pointed out. I think the industry consensus is to not do this, and in-fact normalise around esm as this is "the future" heh.

I guess there are 2 things we actually mean  with respect to esm:
* Esm in (consuming .mjs etc)
* Esm out - Quite interesting reading about how webpack bundle sizes can be reduced quite a bit due to less webpack runtime fluff around referencing modules, so there might be gains here.

A thing that crossed my mind as a possible stopgap on the consumption side was to simply exclude es module calls and defer them onto dynamic `import(path)`. How to do this is more fiddly. I am not sure you can reason that .mjs is definitely a module, or rather not .mjs is commonjs. It would be super cool to be able to consume both formats interchangably.

I found this [cute bit of code](https://2ality.com/2019/10/eval-via-import.html) the other day too for dynamic eval of esmodules as strings. It basically creates data urls and executes them adhoc.

**Comment by ggoodman** [comment]
Here's a demo of what it could look like:

https://plnkr.co/edit/t7LFhZlibeX5ydsY?preview

**Comment by alexswan10k** [comment]
Wow this is really starting to come together, I like it. This gets around the esm execution problem I was having too.

When the bit.dev CDN comes online (prob a few weeks yet), i will have a crack at integrating.. I'l be happy to report back? :)

I must have missed the plugin api, that is IMO a big deal. Its basically an escape hatch to potentially most problems.

As for now, i guess this issue is basically resolved so will close for now - feel free to reopen if you disagree.

**Comment by ggoodman** [comment]
@alexswan10k take a look at this: https://github.com/ggoodman/velcro/pull/26#issue-422321005

Also: https://github.com/ggoodman/velcro#-plugins

Would love your feedback, as always :D
