### ISSUE TITLE
Webpack Warning: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by astanciu** [ggoodman/velcro#6]
![image](https://user-images.githubusercontent.com/1675025/57534558-496b0e80-730e-11e9-999a-1f01dab070b3.png)

**Comment by ggoodman** [comment]
@astanciu just noticed this. Happen to have any more details to look into?

If you're using the browser version of velcro you should add it to webpack's `noParse` as it (IIRC) fully closes over its dependencies.

**Comment by ggoodman** [comment]
Closing. I think this is either obsolete or is no longer an issue for you.
